const ExpenseActionTypes = {
  ADD_EXPENSE: 'ADD_EXPENSE',
  REMOVE_EXPENSE: 'REMOVE_EXPENSE',
  UPDATE_COLLECTIONS_START: 'UPDATE_COLLECTIONS_START',
  UPDATE_COLLECTIONS_SUCCESS: 'UPDATE_COLLECTIONS_SUCCESS',
  UPDATE_COLLECTIONS_FAILURE: 'UPDATE_COLLECTIONS_FAILURE',
  UPDATE_MONTH: 'UPDATE_MONTH',
  UPDATE_YEAR: 'UPDATE_YEAR',
  UPDATE_TABLE: 'UPDATE_TABLE',
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
}

export default ExpenseActionTypes;
